project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550 Quarto"
  site-url: "https://junyi2022.github.io/musa-550-quarto" 
  repo-url: "junyi2022.github.io/musa-550-quarto/" 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Junyi Yang, 2023"

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/MUSA-550-Fall-2023/
        text: "MUSA 550 GitHub"


    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome!
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/wind-data-visulize.ipynb
          - analysis/web-scraping-wave-data.ipynb
          - analysis/3-altair-hvplot.ipynb
          - analysis/4-folium.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




