---
title: "Lake Erie Wind and Wave Data Analysis and Visulization"
subtitle: "Analysis of the Relationship between Wave Height and Wind Strength"
---

## Welcome

This project is a part of my data analysis for my research assistant work. It includes data gathering from multiple sources, visualizations, and regression models. In the analysis tab on the left, you can browse through the process and have a look at the final products for both wind and wave data. The final step includes a regression analysis that is built on all the previous steps.  


### Satisfied requirements
1. Data is collected through a means more sophisticated than downloading (e.g. scraping, API).
2. It combines data collected from 3 or more different sources.
3. The analysis of the data is reasonably complex, involving multiple steps (geospatial joins/operations, data shaping, data frame operations, etc).
4. You analyze raster data using rasterio, rasterstats, or xarray.
5. You perform a machine learning analysis with scikit-learn as part of the analysis.
6. The project includes multiple interactive visualizations that include a significant interactive component (cross-filtering, interactive widgets, etc)  


## Find out more

The code for this repository is hosted on GitHub page: [https://github.com/junyi2022/musa-550-quarto](https://github.com/junyi2022/musa-550-quarto).







 
